package Client;

/**
* Client/ControlHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../client.idl
* Donnerstag, 13. Juni 2002 14.16 Uhr CEST
*/

public final class ControlHolder implements org.omg.CORBA.portable.Streamable
{
  public Client.Control value = null;

  public ControlHolder ()
  {
  }

  public ControlHolder (Client.Control initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Client.ControlHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Client.ControlHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Client.ControlHelper.type ();
  }

}
