package Client;


/**
* Client/ControlHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../client.idl
* Donnerstag, 13. Juni 2002 14.16 Uhr CEST
*/

abstract public class ControlHelper
{
  private static String  _id = "IDL:Client/Control:1.0";

  public static void insert (org.omg.CORBA.Any a, Client.Control that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Client.Control extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Client.ControlHelper.id (), "Control");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Client.Control read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ControlStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Client.Control value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Client.Control narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Client.Control)
      return (Client.Control)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Client._ControlStub stub = new Client._ControlStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
