package HelloApp;


/**
* HelloApp/HelloOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../Hello.idl
* Friday, March 8, 2002 12:42:27 PM CET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
