package Client.ControlPackage;


/**
* Client/ControlPackage/octs4096Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../client.idl
* Donnerstag, 13. Juni 2002 14.16 Uhr CEST
*/


//typedef sequence<octet> octseq;
public final class octs4096Holder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public octs4096Holder ()
  {
  }

  public octs4096Holder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Client.ControlPackage.octs4096Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Client.ControlPackage.octs4096Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Client.ControlPackage.octs4096Helper.type ();
  }

}
