package Server;


/**
* Server/CoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../server.idl
* Donnerstag, 13. Juni 2002 14.16 Uhr CEST
*/

public interface CoordinatorOperations 
{
  Server.Counter register (Client.Control clientObjRef);
  void unregister (Client.Control clientObjRef);
} // interface CoordinatorOperations
