package Server;

/**
* Server/CoordinatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../server.idl
* Donnerstag, 13. Juni 2002 14.16 Uhr CEST
*/

public final class CoordinatorHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Coordinator value = null;

  public CoordinatorHolder ()
  {
  }

  public CoordinatorHolder (Server.Coordinator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.CoordinatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.CoordinatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.CoordinatorHelper.type ();
  }

}
