package Server;

/**
* Server/CounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../server.idl
* Donnerstag, 13. Juni 2002 14.16 Uhr CEST
*/

public final class CounterHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Counter value = null;

  public CounterHolder ()
  {
  }

  public CounterHolder (Server.Counter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.CounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.CounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.CounterHelper.type ();
  }

}
