package Server;


/**
* Server/CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../server.idl
* Donnerstag, 13. Juni 2002 14.16 Uhr CEST
*/

public interface CounterOperations 
{
  int sum ();
  void sum (int newSum);
  int increment ();
} // interface CounterOperations
