package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../Hello.idl
* Freitag, 8. März 2002 13.09 Uhr CET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
